--# selene: allow(roblox_suspicious_udim2_new)

-->insert-repository-warning<--

return {
	CFrame = CFrame,
	Vector2 = Vector2,
	Vector3 = Vector3,
	Color3 = Color3,
	UDim = UDim,
	UDim2 = UDim2,
	PhysicalProperties = PhysicalProperties,
	NumberRange = NumberRange,
	NumberSequence = NumberSequence,
	NumberSequenceKeypoint = NumberSequenceKeypoint,
	ColorSequence = ColorSequence,
	ColorSequenceKeypoint = ColorSequenceKeypoint,
	BrickColor = BrickColor,
}
