-->insert-docs-warning<--

--docname:"clientobjects/Buttons"
--makedocs:
--[[
# Buttons

## ![]({RBX_ICON}/Configuration.png) ButtonConfigurations ![]({RBX_ICON}/Configuration.png)
---
### ![]({RBX_ICON}/NumberValue.png)![]({RBX_ICON}/Vector3Value.png)![]({RBX_ICON}/CFrameValue.png) ButtonPressOffset

This configuration determines the offset that the button moves once it is pressed.

Default value: 0.75

Types:
* number
* Vector3
* CFrame
---
### ![]({RBX_ICON}/StringValue.png) PressedMaterial

This configuration determines the material of the button once it is pressed.

Default value: Neon

Types:
* EnumItem
* string

---
### ![]({RBX_ICON}/StringValue.png) Timer

This configuration determines how long the button will stay pressed.
Will only work if the value is above 0.

Default value: 0

Types:
* number

---
### ![]({RBX_ICON}/StringValue.png) DecimalPlaces


---
### ![]({RBX_ICON}/StringValue.png) TimerText


---
### ![]({RBX_ICON}/StringValue.png) HideGUI


---




## ![]({RBX_ICON}/BasePart.png) ButtonActivatedPlatform ![]({RBX_ICON}/BasePart.png)

---
### ![]({RBX_ICON}/StringValue.png) SetTransparency
---
### ![]({RBX_ICON}/StringValue.png) FullHide
---
### ![]({RBX_ICON}/StringValue.png) Invert
---
### ![]({RBX_ICON}/StringValue.png) ColorOverride
---
### ![]({RBX_ICON}/StringValue.png) IgnoreCanCollide
---
### ![]({RBX_ICON}/StringValue.png) IgnoreTransparency
---
### ![]({RBX_ICON}/StringValue.png) IgnoreAll

help

]]

return nil
