-->insert-docs-warning<--

--docname:"clientobjects/Buttons"
--makedocs:
--[[
# Buttons

### ![]({RBX_ICON}/Configuration.png) ButtonConfigurations ![]({RBX_ICON}/Configuration.png)
---
> ![number]({RBX_ICON}/NumberValue.png)/![Vector3]({RBX_ICON}/Vector3Value.png) /![CFrame]({RBX_ICON}/CFrameValue.png) ButtonPressOffset

This configuration determines the offset that the button moves once it is pressed.

Default value: 0.75

This configuration accepts the following types:
* number
* Vector3
* CFrame
---

### ![]({RBX_ICON}/BasePart.png) ButtonActivatedPlatform ![]({RBX_ICON}/BasePart.png)



]]

return nil
