-- remember to change these values every update!!
-- these version numbers will be applied to the folder and it will allow us to see what kit is being currently used

return {
	Kit = 6.000,
	ClientObjects = {
		-- put client object versions in here ( if needed ! )
		-- this will allow scripts to see what client object version is used, so we can add backwards compatibility for the scripts in the script repository
		Button = 6.00,
		Sequencer = 1.00,
	},
}
