-- warning messages that will be inserted into scripts if requested
return {

	-->insert-repository-warning<--
	["%-%->insert%-repository%-warning<%-%-"] = `--[[\n{[[
--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
												=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
												⚠️  WARNING - PLEASE READ! ⚠️
												-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Please do NOT make any script changes to any repository script that is in this folder.
If you need to make a script edit or want to create a custom repository script, please follow the instructions below:

Create a folder named "RepositoryScripts" in workspace under the Kit folder, and place all of your needed repository scripts there. 
PLEASE NOTE: If you are submitting to JToH, It is important that you include this folder in your submission model, 
			or else any script edits/custom scripts will NOT work in game.
If you are making script edits, please add the following comment "--@edit" to where you did the edit. It will help us a lot!

PS: There is a RepositoryScript template under StarterPlayer.StarterPlayerScripts.Client.RepositoryTemplate if you ever need it.


Once you have read this, and followed all the steps correctly, feel free to remove this comment block.

==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
]]}]]`,

	-->insert-corescript-warning<--
	["%-%->insert%-corescript%-warning<%-%-"] = `--[[\n{[[
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
												-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
												⚠️  WARNING - PLEASE READ! ⚠️
												=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
If you are submitting to JToH: PLEASE, **DO NOT** make any script edits to this script. 
This is a core script and any edits you make to this script will NOT work in JToH.

If you have any suggestions, please let us know.
Thank you

--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
]]}]]`,
}
